package com.aurumiq.app.data.model

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Represents a single daily market record from MCX futures data.
 *
 * Each record corresponds to one trading day for one contract (symbol + expiry).
 * The composite index on (symbol, date, expiryDate) ensures no duplicate records.
 */
@Entity(
    tableName = "market_records",
    indices = [
        Index(value = ["symbol", "date", "expiryDate"], unique = true),
        Index(value = ["symbol"]),
        Index(value = ["date"]),
        Index(value = ["expiryDate"])
    ]
)
data class MarketRecord(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val symbol: String,           // e.g., "GOLDM", "GOLDTEN", "GOLDGUINEA", "GOLDPETAL"
    val date: Long,               // Trading date as epoch millis (UTC midnight)
    val expiryDate: Long,         // Contract expiry date as epoch millis
    val open: Double,
    val high: Double,
    val low: Double,
    val close: Double,
    val volume: Long,
    val openInterest: Long,
    val settlementPrice: Double,
    val dataSource: DataSource = DataSource.DEMO
) {
    /**
     * Validates that this record has sensible values.
     * Returns a list of validation issues (empty if valid).
     */
    fun validate(): List<String> {
        val issues = mutableListOf<String>()
        if (symbol.isBlank()) issues.add("Symbol is blank")
        if (date <= 0) issues.add("Invalid date")
        if (expiryDate <= 0) issues.add("Invalid expiry date")
        if (expiryDate < date) issues.add("Expiry date before trade date")
        if (open <= 0) issues.add("Open price <= 0")
        if (high <= 0) issues.add("High price <= 0")
        if (low <= 0) issues.add("Low price <= 0")
        if (close <= 0) issues.add("Close price <= 0")
        if (high < low) issues.add("High < Low")
        if (open > high || open < low) issues.add("Open outside High-Low range")
        if (close > high || close < low) issues.add("Close outside High-Low range")
        if (volume < 0) issues.add("Negative volume")
        if (openInterest < 0) issues.add("Negative open interest")
        if (settlementPrice <= 0) issues.add("Settlement price <= 0")
        return issues
    }
}

/**
 * Tracks where data originated. Critical for the product's transparency requirement.
 */
enum class DataSource {
    DEMO,       // Synthetic data generated by the app — clearly labeled
    IMPORTED,   // User-imported CSV data
    LIVE        // Reserved for future live feed integration (not in MVP)
}
