package com.aurumiq.app.data.model

/**
 * Represents a trading signal generated by the analytics engine.
 */
data class Signal(
    val date: Long,
    val symbolA: String,
    val symbolB: String,
    val expiryA: Long,
    val expiryB: Long,
    val normalizedPriceA: Double,
    val normalizedPriceB: Double,
    val spreadPercent: Double,
    val zScore: Double,
    val rollingMean: Double,
    val rollingStdDev: Double,
    val volumeA: Long,
    val volumeB: Long,
    val oiA: Long,
    val oiB: Long,
    val liquidityScore: Double,
    val category: SignalCategory,
    val estimatedCostPercent: Double,
    val netSpreadPercent: Double,   // spreadPercent - estimatedCostPercent
    val dataSource: DataSource
)

/**
 * Signal classification categories.
 * Each category has a clear, documented meaning.
 */
enum class SignalCategory(val displayName: String, val description: String) {
    NORMAL(
        "Normal",
        "Spread is within normal statistical range (|z| < threshold)"
    ),
    WATCH(
        "Watch",
        "Spread is approaching threshold (|z| between 1.5 and threshold)"
    ),
    HIGH_RELATIVE_PREMIUM(
        "High Premium",
        "Contract A is trading at a statistically unusual premium to Contract B (z > +threshold)"
    ),
    HIGH_RELATIVE_DISCOUNT(
        "High Discount",
        "Contract A is trading at a statistically unusual discount to Contract B (z < -threshold)"
    ),
    LIQUIDITY_WARNING(
        "Low Liquidity",
        "Signal detected but one or both contracts have insufficient liquidity"
    ),
    INSUFFICIENT_DATA(
        "Insufficient Data",
        "Not enough historical observations to compute reliable statistics"
    )
}
